RECOMMENDATIONS_DB = {
    "Tomato___Bacterial_spot": {
        "probable_cause": "Bacterial infection triggered by humid weather and leaf wetness.",
        "recommendation": "Use copper oxychloride spray and remove infected leaves.",
        "pesticide": "Copper Oxychloride 50% WP",
        "insecticide": "Imidacloprid 17.8% SL (vector control)",
        "dosage": "2 g per 1 liter water",
        "spray_interval_days": 15,
        "estimated_recovery_days": 20,
        "approx_pesticide_cost_inr": 450.0,
        "approx_insecticide_cost_inr": 320.0,
    },
    "Tomato___Early_blight": {
        "probable_cause": "Fungal infection due to warm temperature and old leaf stress.",
        "recommendation": "Spray chlorothalonil/mancozeb and avoid leaf wetness.",
        "pesticide": "Mancozeb 75% WP",
        "insecticide": "Not primary; use only if pest infestation seen",
        "dosage": "2.5 g per 1 liter water",
        "spray_interval_days": 10,
        "estimated_recovery_days": 18,
        "approx_pesticide_cost_inr": 380.0,
        "approx_insecticide_cost_inr": 0.0,
    },
    "Tomato___Late_blight": {
        "probable_cause": "Aggressive fungal outbreak favored by cool and wet conditions.",
        "recommendation": "Use systemic fungicide quickly and improve drainage.",
        "pesticide": "Metalaxyl + Mancozeb",
        "insecticide": "Not mandatory unless sucking pests present",
        "dosage": "2 g per 1 liter water",
        "spray_interval_days": 7,
        "estimated_recovery_days": 14,
        "approx_pesticide_cost_inr": 520.0,
        "approx_insecticide_cost_inr": 0.0,
    },
    "Tomato___Leaf_Mold": {
        "probable_cause": "Fungal growth in dense canopy with poor airflow.",
        "recommendation": "Spray wettable sulfur and improve ventilation.",
        "pesticide": "Sulfur 80% WDG",
        "insecticide": "No dedicated insecticide needed",
        "dosage": "2 g per 1 liter water",
        "spray_interval_days": 12,
        "estimated_recovery_days": 16,
        "approx_pesticide_cost_inr": 340.0,
        "approx_insecticide_cost_inr": 0.0,
    },
    "Tomato___Septoria_leaf_spot": {
        "probable_cause": "Fungal spores spread through splash water and debris.",
        "recommendation": "Apply protective fungicide and avoid overhead irrigation.",
        "pesticide": "Chlorothalonil 75% WP",
        "insecticide": "No direct insecticide required",
        "dosage": "2 g per 1 liter water",
        "spray_interval_days": 10,
        "estimated_recovery_days": 21,
        "approx_pesticide_cost_inr": 430.0,
        "approx_insecticide_cost_inr": 0.0,
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "probable_cause": "Mite infestation in hot and dry microclimate.",
        "recommendation": "Use acaricide and monitor lower leaf surfaces.",
        "pesticide": "Abamectin 1.9% EC",
        "insecticide": "Spiromesifen 22.9% SC",
        "dosage": "0.5 ml per 1 liter water",
        "spray_interval_days": 10,
        "estimated_recovery_days": 15,
        "approx_pesticide_cost_inr": 600.0,
        "approx_insecticide_cost_inr": 520.0,
    },
    "Tomato___Target_Spot": {
        "probable_cause": "Fungal pathogen encouraged by long leaf wetness periods.",
        "recommendation": "Use broad-spectrum fungicide and sanitize crop residue.",
        "pesticide": "Azoxystrobin 23% SC",
        "insecticide": "No dedicated insecticide required",
        "dosage": "1 ml per 1 liter water",
        "spray_interval_days": 10,
        "estimated_recovery_days": 18,
        "approx_pesticide_cost_inr": 700.0,
        "approx_insecticide_cost_inr": 0.0,
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "probable_cause": "Viral infection transmitted by whitefly vectors.",
        "recommendation": "Control whiteflies and remove infected plants early.",
        "pesticide": "Imidacloprid 17.8% SL",
        "insecticide": "Thiamethoxam 25% WG",
        "dosage": "0.3 ml per 1 liter water",
        "spray_interval_days": 12,
        "estimated_recovery_days": 28,
        "approx_pesticide_cost_inr": 550.0,
        "approx_insecticide_cost_inr": 480.0,
    },
    "Tomato___Tomato_mosaic_virus": {
        "probable_cause": "Virus spread via infected tools, sap contact, and seed source.",
        "recommendation": "Destroy infected plants and disinfect farm tools.",
        "pesticide": "No direct curative spray (preventive care)",
        "insecticide": "Mineral oil spray for vector suppression",
        "dosage": "Use preventive hygiene protocol",
        "spray_interval_days": 0,
        "estimated_recovery_days": 30,
        "approx_pesticide_cost_inr": 200.0,
        "approx_insecticide_cost_inr": 350.0,
    },
    "Tomato___healthy": {
        "probable_cause": "No major disease symptom detected in current image.",
        "recommendation": "Plant appears healthy. Continue preventive monitoring.",
        "pesticide": "No pesticide required",
        "insecticide": "No insecticide required",
        "dosage": "N/A",
        "spray_interval_days": 0,
        "estimated_recovery_days": 0,
        "approx_pesticide_cost_inr": 0.0,
        "approx_insecticide_cost_inr": 0.0,
    },
}


def get_recommendation(disease_name: str) -> dict:
    default_item = {
        "probable_cause": "Mixed stress or unclear symptom in single image.",
        "recommendation": "No exact advisory found. Consult local agriculture officer.",
        "pesticide": "General broad-spectrum fungicide/insecticide",
        "insecticide": "Lambda-cyhalothrin 5% EC",
        "dosage": "Follow label dose",
        "spray_interval_days": 10,
        "estimated_recovery_days": 20,
        "approx_pesticide_cost_inr": 500.0,
        "approx_insecticide_cost_inr": 350.0,
    }
    return RECOMMENDATIONS_DB.get(disease_name, default_item)
